version: '3.7'
services:
  rest:
    image: node
    container_name: rest
    working_dir: /app
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
  mongo-db:
    image: mongo
    restart: always
    container_name: mongo-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-db:/data/db
      - mongo-configdb:/data/configdb
#  mongo-express:
#    image: mongo-express
#    restart: always
#    container_name: mongo-express
#    ports:
#      - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: root
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
volumes:
  mongo-db:
    name: mongo-db
    driver: local
  mongo-configdb:
    name: mongo-configdb
    driver: local
